# This is a mechanism for inserting autogenerated content into the READDME file.

function autogenerate_pages(io::IO)
    for stitch in sort(collect(values(SEWING_STITCHES)))
        println(io, "- [$(stitch.iso_number)-$(stitch.name)]($(html_file_name(stitch)))")
    end
end

AUTOGENERATED_RE = r"^ *<!-- +(?<op>BEGIN|END) +AUTOGENERATED +(?<autogen>[a-zA-Z0-9]+) +--> *$"

AUTOGEN_OPS = Dict(
    "Pages" => autogenerate_pages
)


function update_readme()
    readme_file = joinpath(@__DIR__, "README.md")
    input_readme = open(readme_file, "r") do io
        read(io, String)
    end
    open(readme_file, "w") do io
        discarding = false
        for line in split(input_readme, "\n")
            m = match(AUTOGENERATED_RE, line)
            # println(discarding, "\t", m, "\t", line)
            if m == nothing
                if !discarding
                    println(io, line)
                end
            else
                if m[:op] == "BEGIN"
                    println(io, line)
                    discarding = true
                elseif m[:op] == "END"
                    discarding = false
                    # Now generate the new output:
                    AUTOGEN_OPS[m[:autogen]](io)
                    println(io, line)
                else
                    error("Unsupported op in $m")
                end
            end
        end
    end
end

update_readme()

