# Postprocess the SVG generated by Inkspace:
#    * Remove "z" elements from SVG paths.
#    * Change "fill" to "none" in styling.

Pkg.add("EzXML")
using EzXML
using EzXML: ELEMENT_NODE

include("parse_svg_path.jl")

function postprocess_svg(filename::AbstractString)
    doc = readxml(filename)
    postprocess_svg!(doc)
    s = splitext(filename)
    outfile = s[1] * "-postprocessed" * ".svg"
    write(outfile, doc)
end

function postprocess_svg!(doc::EzXML.Document)
    for node in eachnode(root(doc))
        postprocess_svg!(node, Val(node.type))
    end
    doc
end

# Default method
function postprocess_svg!(node::EzXML.Node, ::Any)
end

function postprocess_svg!(node::EzXML.Node, ::Val{ELEMENT_NODE})
    for node in eachnode(node)
        postprocess_svg!(node, Val(node.type))
    end
    postprocess_this!(node, Val(Symbol(nodename(node))))
end

# Default method
function postprocess_this!(node::EzXML.Node, tag::Any)
end

function postprocess_this!(pathnode::EzXML.Node, tag::Val{:path})
    cleanup_path_d!(pathnode)
    # cleanup_path_style!(pathnode)
end

function cleanup_path_d!(pathnode)
    d = pathnode["d"]
    parsed = parse_svg_path(d)
    # Don't modify the path if it's for a punch hole:
    if length(parsed) != 5
        pathnode["d"] = to_string(filter(parsed) do cmd
                                      !isa(cmd, ClosePath)
                                  end)
    end
end

function cleanup_path_style!(pathnode)
    # styles = split(pathnode["style"], ";", keepempty=false)
    pathnode["style"] = "stroke:#000000;fill:none;"
end

